---

  - name: add group dba
    group: name=dba system=yes state=present

  - file: path={{ oracle_base }} state=directory

  - name: add user oracle
    user: name=oracle system=yes group=dba home=/u01/app/oracle shell=/bin/bash state=present

  - file: path={{ oracle_base }}/oracle owner=oracle group=dba recurse=yes state=directory

  - name: install required packages for RedHat
    yum: name={{item}} state=present
    with_items:
      - bc
      - net-tools
      - libaio
      - unzip

  - name: unarchive oracle rpm
    unarchive: src=files/{{ installer_archive }} dest=/tmp

  - name: install oracle xe for Redhat
    yum: name={{ item }} disable_gpg_check=yes disablerepo=* state=installed
    with_items:
      - /tmp/Disk1/{{ installer_rpm }}
